apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  namespace: application
spec:
  selector:
    app: demo-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  type: NodePort
