apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-api
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/maximus-ms/goit-argo.git
    targetRevision: L11
    path: mlflow-inference-api/helm
    helm:
      valuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Replace=true
