replicaCount: 1

image:
  repository: 565493866235.dkr.ecr.us-east-1.amazonaws.com/inference-api
  tag: latest
  pullPolicy: Always

service:
  name: inference-api
  type: ClusterIP
  port: 80
  targetPort: 8000
  annotations: {}

env:
  MLFLOW_TRACKING_URI: http://mlflow.application.svc.cluster.local:5000
  MODEL_NAME: iris_rf_model
  MODEL_STAGE: Production

extraEnvFrom:
  - secretRef:
      name: mlflow-secrets

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

podLabels:
  app: inference-api

livenessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 15

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}